# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: bd
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: bd2
      MYSQL_DATABASE: grupo14
      MYSQL_USER: grupo14
      MYSQL_PASSWORD: password